dev.cfg와 .env 통합
binarysound/random-poll pull request #20
Opened 2017-06-15 11:36 UTC by limgit

## Related Issue
#18 

## Purpose
설정 파일들을 일원화하여 혼란을 막고 consistency problem을 예방합니다

## Overview
 - `dev.cfg`와 `.env`를 통합합니다.

## Comment
 - 맞게 고친건지 모르겠네요. 일단 제 환경 (`Ubuntu 16.04.2 LTS`, `Docker version 17.03.1-ce, build c6d412e`, `docker-compose version 1.13.0, build 1719ceb`)에서는 `$ docker-compose up`으로 앱 올리고 브라우저로 접속해 Hello world! 가 뜨는 것까지 확인했습니다.
 - `README.md`도 수정해야 하네요 😭 깜빡했습니다.. PR 올리고 수정 이어서 달도록 하겠습니다.

2017-06-15 12:03 UTC, JeongHoJeong requested changes
아 이런. 제가 생각한 걸 구체적으로 말씀드렸어야 했는데 제가 실수한 것 같네요.

제 생각은 `configparser` 자체를 아예 들어내고 `.env` 파일만으로 모든 환경 의존적 설정을 하는 것이었습니다. newline 단위로 쪼갠 후 각 줄에 대해 `=`를 delimiter로 삼아 우항만을 취한 후 전역 config dict에 넣어주면 어떨까 합니다.

2017-06-15 13:08 UTC, limgit commented
`OptParser` 말고 `configParser`를 들어내자는 것인가요? 사실 지금 코드가 하고 있는게 정확히 말씀하신대로 동작하기는 합니다. 굳이 그 파싱 과정을 직접 짜는것보다, `configParser`를 살짝 비틀어 이용하는 쪽이 더
 효율적이라 느껴서 14-18번 줄의 형태로 구현해두었습니다.

2017-06-15 13:43 UTC, JeongHoJeong commented
@limgit 음... `OptParser`는 `manager.py`에 필요하게 될 것이지만, `configparser`는 INI 파일이 전혀 사용되지 않는 한 필요가 없는 모듈이라서요. 그리고 INI와 .env의 양식이 다르기도 해서 바로 붙여넣으면 문제가 발생할 겁니다.
 예컨대 .env에선 `#`이 주석의 시작이지만, INI에선 `;`가 시작입니다.

파일 구조가 상당히 간단하기 때문에, 외부 모듈 없이도 다음과 같이 처리해도 되지 않을까요?

```python
config = {}

with open('.env', 'r') as file:
    lines = file.read().split('\n')
    for line in lines:
        line = line.strip()

        if len(line) and line[0] != '#':
            idx = line.find('=')
            name = line[:idx]
            value = line[idx+1:]
            config[name] = value
```

2017-06-15 14:26 UTC, limgit commented
주석은 생각 못했던 문제네요 굳이 저렇게 하느니 파싱 클래스 하나 짜서 해버리죠 뭐

2017-06-16 02:27 UTC, limgit commented
@JeongHoJeong 리뷰 반영했습니다

2017-06-16 03:14 UTC, JeongHoJeong commented
👍 
스쿼시만 완료되면 approve 하겠습니다.

2017-06-16 04:39 UTC, limgit commented
squash 완료했습니다. 확인해주세요.
@JeongHoJeong

2017-06-16 04:47 UTC, JeongHoJeong approved these changes

2017-06-16 04:48 UTC, merged