프로젝트 구조 재구성
binarysound/random-poll pull request #25
Opened 2017-06-16 05:32 UTC by limgit

## Related Issue
#8 

## Purpose
보기 좋은 떡이 먹기도 좋다고 하죠. 프로젝트 구조를 재구성하여 파일을 정돈하고 유지보수성을 높입니다.

## Overview
#8 이슈에서 논의했던 대로 디렉토리를 구성합니다.

## Comment
 - 현재 작업이 들어간 부분이 `main.py`밖에 없는 관계로, 디렉토리에서의 변경은 `app/` 이 추가되고 그 안으로 `main.py`가 들어간 것 밖에 없습니다.
 - `main.py`의 위치가 바뀌었기 때문에 `Dockerfile`에서 `WORKDIR`을 바꾸어주는 한 줄을 삽입했습니다.
 - `Dockerfile`이 수정되었기 때문에 이미지를 다시 빌드해야 합니다. 방법은 #24 PR에서 했던것과 마찬가지로 `$ docker-compose build`입니다. 빌드하며 실행하기 위해서는 `$ docker-compose up --build`도 가능합니다.
 - `.env`와 `Dockerfile`이 프로젝트 루트에 있기 때문에 `docker` 관련 실행 명령은 모두 프로젝트 루트에서 실행해야 합니다.

2017-06-16 08:19 UTC, JeongHoJeong requested changes
`Dockerfile`에서 `WORKDIR`을 수정하지 않는 대신, 이 PR에서 프로젝트 루트에 `manage.py`를 두어 이 파일이 `main.py`의 주요 루틴을 실행하게 하는 게 어떨까요? 그 경우 `Dockerfile` 최하단의 `CMD`가 `main.py` 대신 `manage.py run`을 호출하는 식이 될 것 같습니다. 작업이 좀 커지긴 합니다만 꼭 해야 할 일로 보여 이렇게 제안드립니다.

이 경우 각 파일 구조가 다음과 같이 세분화될 것 같네요.

|파일|기능|
|-|-|
|`./manage.py`|`OptionParser`를 이용한 명령행 분석, `.env` 분석 및 메인 루틴 실행|
|`./app/main.py`|Flask 메인 루틴|

2017-06-16 08:27 UTC, limgit commented
`manage.py`를 이 PR에서 넣을지 말지 고민하고 있었는데 넣는 방향이 되겠군요.

그러면 `app/main.py`에서는 Flask 루틴만 넣고, `.env` 파싱등의 작업은 전부 `manage.py`에서 하게 되겠네요. `app/main.py`가 인자로 `.env`를 파싱한 결과를 받을 수 있게 해야겠군요

@JeongHoJeong

2017-06-16 08:30 UTC, JeongHoJeong commented
@limgit 넵. 아주 좋습니다. 실제 실행부는 클래스로 묶어 싱글톤으로 마련하는 등의 방법도 좋을 것 같아요.

2017-06-16 15:03 UTC, limgit commented
일단 `manage.py` 파일을 만들고 그에 따라 `Dockerfile`과 `app/main.py`를 수정했습니다. 큰 틀은 제대로 잡힌것 같은데 세부 구현이 어찌될지 모르겠네요. 리뷰 부탁드립니다.
@JeongHoJeong 

P.S. ssh로 작업하면 한글이 입력이 안되네요 😭 최종 squash할때는 커밋 메시지 전부 한글로 할게요 ㅠㅠ

2017-06-17 07:11 UTC, JeongHoJeong commented on manage.py
> +class EnvParser(object):
Top-level class는 두 개의 blank line으로 감싸는 것이 좋을 것 같습니다. [(PEP8)](https://www.python.org/dev/peps/pep-0008/#blank-lines)

하는 김에 [Docstring](https://www.python.org/dev/peps/pep-0257/)도 제공하면 어떨까요?

2017-06-17 07:13 UTC, JeongHoJeong commented on manage.py
> +                if line[0] == "#": pass  # This is comment line
`pass`가 아니라 `continue`여야 하지 않나요?
또, 비록 한 줄짜리 명령이긴 하지만 두 줄로 구분하는 것이 보다 명확할 것 같습니다.

2017-06-17 07:14 UTC, JeongHoJeong commented on manage.py
> +                    exit(1)
Exception을 던지는 쪽이 더 맞을 것 같습니다. `EnvParser`의 역할은 파싱 자체에 있기 때문에, 프로그램의 라이프사이클에는 연관이 있으면 안 될 것 같습니다.

2017-06-17 07:15 UTC, limgit commented on manage.py
> +                if line[0] == "#": pass  # This is comment line
음주코딩의 폐해라고 하죠....(._.

2017-06-17 07:16 UTC, limgit commented on manage.py
> +class EnvParser(object):
PEP8 컨벤션을 알긴 하는데 어차피 Pylint 적용하면서 한번 전체적으로 스타일링 잡힐거라 코드 스타일엔 크게 신경을 안썼습니다.

닥스트링...은 귀찮긴 한데 해볼게요 😢

2017-06-17 07:20 UTC, JeongHoJeong requested changes
클래스로 나뉘면서 구조가 점점 보기 좋아지는 것 같습니다. 슬슬 코딩다운 코딩이 가능하겠네요.. 👍

2017-06-17 07:20 UTC, JeongHoJeong commented on manage.py
> +            exit(1)
마찬가지로 Exception 처리가 더 나을 것 같습니다.

2017-06-17 07:26 UTC, JeongHoJeong commented on manage.py
> +class CommandParser(object):
`CommandParser`의 역할이 파싱 자체에만 국한된 게 아니라 앱의 실행 전반에 관여하는 것 같습니다. `App` 등의 이름은 어떨까요?

2017-06-17 12:23 UTC, limgit commented on manage.py
> +class CommandParser(object):
이름을 `CommandParser`로 한 이유는 class의 존재 목적이 '`command`를 파싱하고, 그에 따른 명령을 실행한다'였기 때문입니다. `AppInitializer`은..... 맘에 들진 않ㅇ는데 딱히 대안이 떠오르지는 않네요 ㅠㅠ

2017-06-17 12:35 UTC, JeongHoJeong commented on manage.py
> +class CommandParser(object):
`AppManager`나 `Launcher`...? 정도는 어떤가요? 사실 이름이 'Command **Parser**'인 점이 걸리는 부분입니다. 실질적인 파싱 이상의 기능적인 부분까지 갖추고 있어서요.

2017-06-17 12:49 UTC, limgit commented
리뷰 반영했습니다.
@JeongHoJeong

2017-06-17 13:54 UTC, JeongHoJeong requested changes
코드가 아주 깔끔해져서 다른 작업 올리기가 수월할 것 같습니다. Docstring 얘기는 클래스 머리에만 다는 걸 말씀드린 것이었는데, 전부 달아 주셨네요! 😮👏👏

사소한 몇 부분만 수정해주시면 approve 하겠습니다.

2017-06-17 13:54 UTC, JeongHoJeong commented on manage.py
> +    This class has function parse, which parses the .env file
사소하지만 `parse`를 `` `parse` ``로 표현해주면 어떨까요? 그러면 어떤 것이 identifier인지 좀 더 명확할 것 같습니다.

2017-06-17 13:54 UTC, JeongHoJeong commented on manage.py
> +    and returns the dictionary value according to .env file
Docstring이 문장을 이루고 있으니 마지막에 마침표를 찍어주면 어떨까요?

2017-06-17 13:54 UTC, JeongHoJeong commented on manage.py
> +        parser and list the available subcommands for manage.py
`list` -> `lists`?

2017-06-17 13:54 UTC, JeongHoJeong commented on manage.py
> +        with unbuffered output mode.
[Writefull](https://writefullapp.com/)에 따르면 `run with ~ mode`보다 `run in ~ mode`가 더 일반적인 것 같습니다.

![image](https://user-images.githubusercontent.com/11784631/27253234-c3d5e994-53ab-11e7-9b2f-798516f6b0a4.png)

2017-06-17 13:54 UTC, JeongHoJeong commented on manage.py
> +        If subcommand is not available, it raises ValueError
위와 마찬가지로 `ValueError` 대신 `` `ValueError` ``는 어떨까요?

2017-06-17 13:54 UTC, JeongHoJeong commented on manage.py
> +        subprocess.call(["python", "-u", "main.py", "--db-password", env["DB_PASSWORD"]])
이전 리뷰에서 짚었어야 했는데 놓친 것 같습니다. `subprocess`를 말씀하실 떄 말씀드렸어야 했는데 제가 실수했네요.

제가 원래 생각했던 건 프로세스 포크를 하는 게 아니라 `main.py`를 모듈처럼 써서 `App.run()`을 호출하는 형태였습니다. 이유가 있다면 우선 지금 형태라면 여기서 기껏 받아놓은 config를 전달하는 데 또 로직이 있어야 하고, 굳이 프로세스가 더 들어갈 필요가 없는데 한 레이어가 더 들어가는 점이 그렇습니다.

이 PR은 일단 다른 부분만 해결되면 머지하고, 서버 실행부 로직에 관련된 부분은 다른 이슈에서 논의하는 게 나을 것 같습니다.

2017-06-17 14:03 UTC, JeongHoJeong commented on manage.py
> +
없어도 되는 라인 하나가 더 있는 것 같습니다.

2017-06-17 14:55 UTC, JeongHoJeong commented on manage.py
> +        self._available_subcommands = ["run"]
변하지 않아야 할 값이니 [class constant](https://stackoverflow.com/a/69067)로 선언해도 될 것 같습니다.

2017-06-17 16:47 UTC, limgit commented on manage.py
> +        subprocess.call(["python", "-u", "main.py", "--db-password", env["DB_PASSWORD"]])
이부분은 저도 그렇게 하려 했는데, 그러면 `app/` 내부에 `__init__.py`를 만들어서 `app/`을 패키지화 해줘야 하기도 하고, 애초에 지금 `main.py` 자체가 뭔가 실행부를 함수 하나로 분리해 둔 상태가 아니고 그냥 다 풀어둔 코드이기 때문에 그렇게 진행하기 어려워서 뺀 점도 있습니다.

2017-06-17 17:01 UTC, limgit commented on manage.py
> +
기본적으로 PEP 8 은 파일의 가장 마지막에 newline character 하나를 두는 것을 권장합니다 ([이 문서](http://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes)의 W292 에러 코드를 보시면 에러 이름이 "no newline at end of file입니다). 그리고 [이 Stack Overflow 답변](https://stackoverflow.com/a/5813359)에서도 보듯이, git 기반으로 작업을 할 때는 기본적으로 모든 파일의 끝에 newline character를 붙여주는 것이 diff의 출력에 있어서 결과를 더 보기 좋게 만들기 때문에 이를 권장하고 있습니다.

2017-06-17 17:02 UTC, limgit commented on manage.py
> +    This class has function parse, which parses the .env file
안그래도 identifier가 어느것인지 불명확한 문제가 있었는데 그런 방법이 있었네요

2017-06-17 17:03 UTC, JeongHoJeong commented on manage.py
> +
아 그게.. 빈 줄이 하나가 아닌 두 개가 있는 것 같아서 드린 말씀이었습니다. 제가 에디터로 열어서 확인할 때는 그렇게 보이네요.

2017-06-17 17:21 UTC, limgit commented on manage.py
> +
일단 git diff에서도 이 129번째 줄이 마지막 줄이고 제 vim 에디터에서도 빈 줄은 하나만 나오긴 하네요
![image](https://user-images.githubusercontent.com/10260432/27254868-c5f04316-53cc-11e7-9e41-e5733fd4725d.png)

2017-06-17 18:02 UTC, JeongHoJeong commented
👍

2017-06-18 08:44 UTC, limgit commented
@JeongHoJeong squash 마쳤습니다. 레이블 뗴고 approve 상태로 돌려주시면 머지하겠습니다

2017-06-18 08:49 UTC, JeongHoJeong approved these changes

2017-06-18 09:03 UTC, merged