Pylint 적용
binarysound/random-poll pull request #27
Opened 2017-06-19 07:06 UTC by limgit

## Related Issue
#19 

## Purpose
코드 정적 분석기를 적용하여 버그를 미연에 방지하고 통일된 코드 스타일을 유지합니다.

## Overview
Pylint를 적용하고, 이를 `manage.py`에서 다룰 수 있도록 합니다. 변경 사항은 아래와 같습니다.
 - `requirements.txt`에 pylint 추가
 - `test_pylint.py` 작성
 - `pylintrc` 파일을 명령어로 생성하고 필요한 부분 변경
   - output-format=colorized 로 변경
 - `manage.py`에 test subcommand 추가
 - pylint의 경고에 맞게 몇가지 간단한 refactor 진행
 - tests 폴더를 모듈로 인식하도록 빈 `__init__.py` 추가

## Comment
 - docker 내에서 테스트를 돌려보진 않았으나, 우분투 환경에서 pyenv로 필요한 패키지 깔고 테스트는 전부 해봤습니다.
 - `tests/test_pylint.py`를 직접 이용하는 경우
   - `$ python test_pylint.py` 를 실행할 경우, 프로젝트 내의 모든 `.py` 파일을 pylint로 분석합니다.
   - `$ python test_pylint.py -t <path>`  (or `$ python test_pylint.py --target <path>`)를 실행할 경우 (단 `<path>`는 프로젝트 루트를 기준으로 한 상대경로입니다.)
     - `<path>`가 파일이라면 (ex. `app/main.py`) 해당 파일을 pylint로 분석합니다.
     - `<path>`가 디렉토리라면 (ex. `app/`) 해당 디렉토리 내 모든 파일을 pylint로 분석합니다.
 - `manage.py`를 이용하는 경우
   - `$ python manage.py test`는 `tests/test_full.py`를 invoke 합니다. 다만 아직 `tests/test_full.py`가 구현되어 있지 않아 지금은 아무 행동도 하지 않습니다.
   - `$ python manage.py test -l [path]` (or `$ python manage.py test --lint [path]`)은 `tests/test_pylint.py`를 invoke 합니다.
     - `path`가 주어져 있다면, `$ python test_pylint.py -t path`를 한 것과 같은 효과가 납니다. 즉, 주어진 경로가 파일이라면 파일을, 디렉토리라면 디렉토리 내 모든 파일을 pylint로 분석합니다. 여기서 경로는 반드시 프로젝트 루트를 기준으로 한 경로여야 합니다.
     - `path`가 주어져 있지 않다면, `$ python test_pylint.py`를 한 것과 같은 효과가 납니다. 즉 프로젝트 내 모든 `.py` 파일을 pylint로 분석합니다.
 - `tests/test_pylint.py`는 현재 디렉토리에서 위로 올라가며 가장 처음 만나는 `.git/`이 있는 디렉토리를 프로젝트 루트로 간주합니다. 이 방법은 `ctrlp.vim`를 참고하였습니다.

2017-06-19 07:39 UTC, JeongHoJeong requested changes
수고 많으셨습니다. 코드가 더더욱 끌깜해지겠네영

2017-06-19 07:39 UTC, JeongHoJeong commented on manage.py
> +        parser.add_argument("-l", "--lint", nargs="?", metavar="FILE", default=Args.NOT_GIVEN,
인자가 많으니 다음과 같이 indent 처리하면 어떨까요?

```python
parser.add_argument(
  "-l", "--lint", # ...
)
```

2017-06-19 07:39 UTC, JeongHoJeong commented on manage.py
> +
한 줄이 더 있는 것 같긴 한데요... pylint가 뭐라고 하나 봐야긴 하겠습니다.

2017-06-19 07:39 UTC, JeongHoJeong commented on manage.py
> +            usage="manage.py run [<args>]")
끝의 괄호를 다음 줄로 내리는 컨벤션으로 정하면 어떨까요? chaining이 편해집니다.

```python
foo.xxx(
  # ...
).yyy(
  # ...
).zzz(
  # ...
)
```

2017-06-19 08:56 UTC, limgit commented on manage.py
> +
일단 pylint 자체에선 아무 경고가 없긴 하네요.  이게 설정으로 경고 옵션을 켤 수 있는지는 좀 더 알아봐야 할 것 같습니다.  없다면 PEP8이랑 pylint를 스까쓰는것도 괜찮을 것 같...긴 한데....

아 그리고 알아보는거랑 별개로 이 줄은 필요 없으니까 지울게요.

2017-06-19 09:00 UTC, limgit commented on manage.py
> +
PEP8에서 해당 항목과 관련된에러 코드가 [E3](http://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes)번대 에러 코드인데 이 [Stack Overflow 답변](https://stackoverflow.com/a/7441902)에 따르면 pylint에서는 지원되지 않는 것 같네요.

2017-06-20 02:19 UTC, limgit commented
스타일링 조금 손봤고, pylint 설정도 손봤습니다. 자세한건 커밋 세부 메시지 참조해주세요.

2017-06-24 07:25 UTC, JeongHoJeong approved these changes

2017-06-24 07:25 UTC, merged